#!/usr/bin/env php
<?php
require dirname(__DIR__) . '/vendor/autoload.php';

/**
 * This example shows how to use a stream to read a file.
 *
 * Note that PHP's fopen() function is NOT asynchronous.
 */

use Recoil\Recoil;

Recoil::run(
    function () {
        $stream = new \Recoil\Stream\ReadablePhpStream(fopen(__FILE__, 'r'));

        while (!$stream->isClosed()) {
            echo (yield $stream->read(512));
        }

        echo PHP_EOL;
    }
);
