#!/usr/bin/env php
<?php

/**
 * This example shows how to asynchronously read from a stream.
 */

declare(strict_types = 1);

require __DIR__ . '/../vendor/autoload.php';


use Recoil\React\ReactKernel;
use Recoil\Recoil;

ReactKernel::start(function () {
    $fp = tmpfile(); // please note that this is a *blocking* file operation
    stream_set_blocking($fp, false);
    stream_set_read_buffer($fp, 0);

    $buffer = "<line 1>\n<line 2>\n";

    while ($buffer) {
        list(, $write) = yield Recoil::select(null, [$fp]);

        $bytes = fwrite($fp, $buffer);
        $buffer = substr($buffer, $bytes);
    }

    fseek($fp, 0);

    while (!feof($fp)) {
        list($read) = yield Recoil::select([$fp]);
        echo fread($fp, 16);
    }

    fclose($fp);
});
