#!/usr/bin/env php
<?php
require dirname(__DIR__) . '/vendor/autoload.php';

use Icecave\Recoil\Kernel\Kernel;

$f = function () {
    echo 'HI';
    return;
    yield;
};

$kernel = new Kernel;

$kernel->execute($f());

$kernel->eventLoop()->run();
